name: Python application

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-22.04
    container:
      image: ubuntu:20.04

    steps:
      - name: apt-get
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y unzip curl git autoconf build-essential ca-certificates tzdata
      - name: check glibc version
        run: ldd --version
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install --upgrade pyinstaller
          pip install pyinstaller-versionfile
      - name: Build binary
        run: |
          pyinstaller --clean --noconfirm --onefile --nowindow --distpath dist/ --workpath /tmp CxOneCli.py
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }} ${{ github.workspace }}/dist/* --generate-notes --title "Version ${{ github.ref_name }}"
